/*
 * Copyright (c) 2014 Juniper Networks, Inc. All rights reserved.
 */

/* This file is automatically generated from the parseURL.xml at
   Mon Oct 26 2015 09:56:25 GMT+0530 (IST)
   Please do not edit this file.
 */

var parseURLReq = require(process.mainModule.exports["corePath"] + '/src/serverroot/common/parseURLRequire')
  , virtualdnsconfigapi = require('./virtualdnsconfig.api')
  ;


if (!module.parent) {
  console.log("Call main app through 'node app'");
  process.exit(1);
}
urlRoutes = module.exports;

/* Default handler for request timeout */
function defHandleReqTimeout (req, res)
{
  var str = "Request timed out: URL::" + req.url;
  if (req.pubChannel) {
    /* Delete the Req Pending Q Entry */
    parseURLReq.cacheApi.deleteCachePendingQueueEntry(req.pubChannel);
  };
  res.req.invalidated = true;
  res.send(parseURLReq.global.HTTP_STATUS_GATEWAY_TIMEOUT, str);
}

urlRoutes.registerURLsToApp = function(app) {
/* Register the URL with callback */
  app.get('/api/tenants/config/virtual-DNSs/:id', virtualdnsconfigapi_listVirtualDNSs);
  app.get('/api/tenants/config/virtual-DNSs', virtualdnsconfigapi_listVirtualDNSsFromAllDomains);
  app.post('/api/tenants/config/virtual-DNSs', virtualdnsconfigapi_createVirtualDNS);
  app.delete('/api/tenants/config/virtual-DNS/:id', virtualdnsconfigapi_deleteVirtualDNS);
  app.get('/api/tenants/config/virtual-DNS/:id', virtualdnsconfigapi_getVirtualDNS);
  app.post('/api/tenants/config/virtual-DNS/:id/virtual-DNS-records', virtualdnsconfigapi_updateVDNSRecordAdd);
  app.delete('/api/tenants/config/virtual-DNS/:id/virtual-DNS-record/:recordid', virtualdnsconfigapi_updateVDNSRecordDelete);
  app.put('/api/tenants/config/virtual-DNS/:id/network-ipams', virtualdnsconfigapi_updateVDNSIpams);
  app.put('/api/tenants/config/virtual-DNS/:id/virtual-DNS-record/:recordid', virtualdnsconfigapi_updateVDNSRecordUpdate);
  app.put('/api/tenants/config/virtual-DNS/:id', virtualdnsconfigapi_updateVirtualDNS);
  app.get('/api/tenants/config/sandesh/virtual-DNS/:dnsfqn', virtualdnsconfigapi_getVirtualDNSSandeshRecords);


  parseURLReq.rbac.setFeatureByURL('/api/tenants/config/virtual-DNSs/:id', 'get', app.routes, 'virtualdnsconfig');
  parseURLReq.rbac.setFeatureByURL('/api/tenants/config/virtual-DNSs', 'get', app.routes, 'virtualdnsconfig');
  parseURLReq.rbac.setFeatureByURL('/api/tenants/config/virtual-DNSs', 'post', app.routes, 'virtualdnsconfig');
  parseURLReq.rbac.setFeatureByURL('/api/tenants/config/virtual-DNS/:id', 'delete', app.routes, 'virtualdnsconfig');
  parseURLReq.rbac.setFeatureByURL('/api/tenants/config/virtual-DNS/:id', 'get', app.routes, 'virtualdnsconfig');
  parseURLReq.rbac.setFeatureByURL('/api/tenants/config/virtual-DNS/:id/virtual-DNS-records', 'post', app.routes, 'virtualdnsconfig');
  parseURLReq.rbac.setFeatureByURL('/api/tenants/config/virtual-DNS/:id/virtual-DNS-record/:recordid', 'delete', app.routes, 'virtualdnsconfig');
  parseURLReq.rbac.setFeatureByURL('/api/tenants/config/virtual-DNS/:id/network-ipams', 'put', app.routes, 'virtualdnsconfig');
  parseURLReq.rbac.setFeatureByURL('/api/tenants/config/virtual-DNS/:id/virtual-DNS-record/:recordid', 'put', app.routes, 'virtualdnsconfig');
  parseURLReq.rbac.setFeatureByURL('/api/tenants/config/virtual-DNS/:id', 'put', app.routes, 'virtualdnsconfig');
  parseURLReq.rbac.setFeatureByURL('/api/tenants/config/sandesh/virtual-DNS/:dnsfqn', 'get', app.routes, 'virtualdnsconfig');
}
virtualdnsconfigapi_listVirtualDNSs = function(req, res, next) {
  /* Check if this request needs to be added in 
     pendingQ 
   */
  var reqCtx = parseURLReq.longPoll.routeAll(req, res, next);
  if (null == reqCtx) {
    /* either not a valid URL, or unAuthed session */
  } else {
    /* Set the request timeout */
    parseURLReq.timeout(req, res, parseURLReq.global.DFLT_HTTP_REQUEST_TIMEOUT_TIME);
    req.once('timeout', defHandleReqTimeout);
    /* Now process the resuest */
    parseURLReq.longPoll.processPendingReq(reqCtx, next, virtualdnsconfigapi.listVirtualDNSs);
  }
}
virtualdnsconfigapi_listVirtualDNSsFromAllDomains = function(req, res, next) {
  /* Check if this request needs to be added in 
     pendingQ 
   */
  var reqCtx = parseURLReq.longPoll.routeAll(req, res, next);
  if (null == reqCtx) {
    /* either not a valid URL, or unAuthed session */
  } else {
    /* Set the request timeout */
    parseURLReq.timeout(req, res, parseURLReq.global.DFLT_HTTP_REQUEST_TIMEOUT_TIME);
    req.once('timeout', defHandleReqTimeout);
    /* Now process the resuest */
    parseURLReq.longPoll.processPendingReq(reqCtx, next, virtualdnsconfigapi.listVirtualDNSsFromAllDomains);
  }
}
virtualdnsconfigapi_createVirtualDNS = function(req, res, next) {
  /* Check if this request needs to be added in 
     pendingQ 
   */
  var reqCtx = parseURLReq.longPoll.routeAll(req, res, next);
  if (null == reqCtx) {
    /* either not a valid URL, or unAuthed session */
  } else {
    /* Set the request timeout */
    parseURLReq.timeout(req, res, parseURLReq.global.DFLT_HTTP_REQUEST_TIMEOUT_TIME);
    req.once('timeout', defHandleReqTimeout);
    /* Now process the resuest */
    parseURLReq.longPoll.processPendingReq(reqCtx, next, virtualdnsconfigapi.createVirtualDNS);
  }
}
virtualdnsconfigapi_deleteVirtualDNS = function(req, res, next) {
  /* Check if this request needs to be added in 
     pendingQ 
   */
  var reqCtx = parseURLReq.longPoll.routeAll(req, res, next);
  if (null == reqCtx) {
    /* either not a valid URL, or unAuthed session */
  } else {
    /* Set the request timeout */
    parseURLReq.timeout(req, res, parseURLReq.global.DFLT_HTTP_REQUEST_TIMEOUT_TIME);
    req.once('timeout', defHandleReqTimeout);
    /* Now process the resuest */
    parseURLReq.longPoll.processPendingReq(reqCtx, next, virtualdnsconfigapi.deleteVirtualDNS);
  }
}
virtualdnsconfigapi_getVirtualDNS = function(req, res, next) {
  /* Check if this request needs to be added in 
     pendingQ 
   */
  var reqCtx = parseURLReq.longPoll.routeAll(req, res, next);
  if (null == reqCtx) {
    /* either not a valid URL, or unAuthed session */
  } else {
    /* Set the request timeout */
    parseURLReq.timeout(req, res, parseURLReq.global.DFLT_HTTP_REQUEST_TIMEOUT_TIME);
    req.once('timeout', defHandleReqTimeout);
    /* Now process the resuest */
    parseURLReq.longPoll.processPendingReq(reqCtx, next, virtualdnsconfigapi.getVirtualDNS);
  }
}
virtualdnsconfigapi_updateVDNSRecordAdd = function(req, res, next) {
  /* Check if this request needs to be added in 
     pendingQ 
   */
  var reqCtx = parseURLReq.longPoll.routeAll(req, res, next);
  if (null == reqCtx) {
    /* either not a valid URL, or unAuthed session */
  } else {
    /* Set the request timeout */
    parseURLReq.timeout(req, res, parseURLReq.global.DFLT_HTTP_REQUEST_TIMEOUT_TIME);
    req.once('timeout', defHandleReqTimeout);
    /* Now process the resuest */
    parseURLReq.longPoll.processPendingReq(reqCtx, next, virtualdnsconfigapi.updateVDNSRecordAdd);
  }
}
virtualdnsconfigapi_updateVDNSRecordDelete = function(req, res, next) {
  /* Check if this request needs to be added in 
     pendingQ 
   */
  var reqCtx = parseURLReq.longPoll.routeAll(req, res, next);
  if (null == reqCtx) {
    /* either not a valid URL, or unAuthed session */
  } else {
    /* Set the request timeout */
    parseURLReq.timeout(req, res, parseURLReq.global.DFLT_HTTP_REQUEST_TIMEOUT_TIME);
    req.once('timeout', defHandleReqTimeout);
    /* Now process the resuest */
    parseURLReq.longPoll.processPendingReq(reqCtx, next, virtualdnsconfigapi.updateVDNSRecordDelete);
  }
}
virtualdnsconfigapi_updateVDNSIpams = function(req, res, next) {
  /* Check if this request needs to be added in 
     pendingQ 
   */
  var reqCtx = parseURLReq.longPoll.routeAll(req, res, next);
  if (null == reqCtx) {
    /* either not a valid URL, or unAuthed session */
  } else {
    /* Set the request timeout */
    parseURLReq.timeout(req, res, parseURLReq.global.DFLT_HTTP_REQUEST_TIMEOUT_TIME);
    req.once('timeout', defHandleReqTimeout);
    /* Now process the resuest */
    parseURLReq.longPoll.processPendingReq(reqCtx, next, virtualdnsconfigapi.updateVDNSIpams);
  }
}
virtualdnsconfigapi_updateVDNSRecordUpdate = function(req, res, next) {
  /* Check if this request needs to be added in 
     pendingQ 
   */
  var reqCtx = parseURLReq.longPoll.routeAll(req, res, next);
  if (null == reqCtx) {
    /* either not a valid URL, or unAuthed session */
  } else {
    /* Set the request timeout */
    parseURLReq.timeout(req, res, parseURLReq.global.DFLT_HTTP_REQUEST_TIMEOUT_TIME);
    req.once('timeout', defHandleReqTimeout);
    /* Now process the resuest */
    parseURLReq.longPoll.processPendingReq(reqCtx, next, virtualdnsconfigapi.updateVDNSRecordUpdate);
  }
}
virtualdnsconfigapi_updateVirtualDNS = function(req, res, next) {
  /* Check if this request needs to be added in 
     pendingQ 
   */
  var reqCtx = parseURLReq.longPoll.routeAll(req, res, next);
  if (null == reqCtx) {
    /* either not a valid URL, or unAuthed session */
  } else {
    /* Set the request timeout */
    parseURLReq.timeout(req, res, parseURLReq.global.DFLT_HTTP_REQUEST_TIMEOUT_TIME);
    req.once('timeout', defHandleReqTimeout);
    /* Now process the resuest */
    parseURLReq.longPoll.processPendingReq(reqCtx, next, virtualdnsconfigapi.updateVirtualDNS);
  }
}
virtualdnsconfigapi_getVirtualDNSSandeshRecords = function(req, res, next) {
  /* Check if this request needs to be added in 
     pendingQ 
   */
  var reqCtx = parseURLReq.longPoll.routeAll(req, res, next);
  if (null == reqCtx) {
    /* either not a valid URL, or unAuthed session */
  } else {
    /* Set the request timeout */
    parseURLReq.timeout(req, res, parseURLReq.global.DFLT_HTTP_REQUEST_TIMEOUT_TIME);
    req.once('timeout', defHandleReqTimeout);
    /* Now process the resuest */
    parseURLReq.longPoll.processPendingReq(reqCtx, next, virtualdnsconfigapi.getVirtualDNSSandeshRecords);
  }
}
